version: '3'
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - net1
  web:
    depends_on:
      - redis
    build: .
    restart: always
    ports:
      - "3000:3000"
    networks:
      - net1
networks:
  net1:
    driver: bridge
