/* Action types */

export const TOGGLE_TITLE_STATE = 'TOGGLE_TITLE_STATE';
export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const INVALIDATE_EVENTS = 'INVALIDATE_EVENTS';
export const SHOW_MODAL_LOADER = 'SHOW_MODAL_LOADER';
export const HIDE_MODAL_LOADER = 'HIDE_MODAL_LOADER';
export const PERFORM_ADMIN_LOGIN = 'PERFORM_ADMIN_LOGIN';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CREATE_EVENT = 'CREATE_EVENT';
export const REDIRECT_OFF_PAGE = 'REDIRECT_OFF_PAGE';
export const LOADING = 'LOADING';
export const NOT_LOADING = 'NOT_LOADING';
export const API_ERROR = 'API_ERROR';
export const EVENT_UPSERT = 'EVENT_UPSERT';
export const DELETE_DATA_LOCALLY = 'DELETE_DATA_LOCALLY';
export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const USER_UPSERT = 'USER_UPSERT';
export const UPDATE_DASHBOARD_CARDS = 'UPDATE_DASHBOARD_CARDS';
export const MARK_ATTENDING = 'MARK_ATTENDING';
export const MARK_UNATTENDING = 'MARK_UNATTENDING';
