/* Action types */

export const TOGGLE_TITLE_STATE = 'TOGGLE_TITLE_STATE';
export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const INVALIDATE_EVENTS = 'INVALIDATE_EVENTS';
export const SHOW_MODAL_LOADER = 'SHOW_MODAL_LOADER';
export const HIDE_MODAL_LOADER = 'HIDE_MODAL_LOADER';
export const PERFORM_ADMIN_LOGIN = 'PERFORM_ADMIN_LOGIN';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED';